version: '3.7'

services:
  mqtt:
    image: GE_CONNECT
    environment:
      - MQTT_HOST=mqtt://10.246.0.10:1883
      - MQTT_PORT=8883
      - MQTT_CLIENTID=95cb7981-3d4c-4b35-aff0-73d5150be1be
      - MQTT_USERNAME=gepc-producer
      - MQTT_PASSWORD=26afc6e1
    ports:
      - "1883:1883"
      - "8883:8883"
    restart: always
